### ISSUE TITLE
LibreSpeed Support

### ISSUE THREAD

**Issue by lealog** [wifinigel/wiperf#11]
Hi Nigel,

Can you please evaluate if is possible to add support for LibreSpeed (https://github.com/librespeed) speedtest tool. I saw that you support speedtest via cli (speedtest.net). Can you also support LibreSpeed via cli (https://github.com/librespeed/speedtest-cli)?

Thanks.

**Comment by wifinigel** [comment]
I had a look at this and its unlikely in the short term unless a Python client module becomes available. I'll keep this under review.

**Comment by wifinigel** [comment]
Done in v2.1

**Comment by lealog** [comment]
Thanks. Is working fine :) I'm using my own librespeed server in my local network and the results are stable.
