### ISSUE TITLE
Store Data Locally in CSV/JSON format

### ISSUE THREAD

**Issue by wifinigel** [wifinigel/wiperf#24]
V2.1

Store results data locally in CSV/JSON format (e.g. 1 week) to allow local inspection and possibly other remote retrieval methods.

**Comment by lealog** [comment]
Thanks.

**Comment by wifinigel** [comment]
Implementation details:
1. Store files in one folder per day in /var/cache/wiperf/<day number>
2. config.ini will have params to configure number of days to be retained and format (csv or json)
3. One file per test type per day (e.g. http, smb, ping etc.)
4. Delete oldest folder one number of day folders exceeds retention policy specified in config.ini
