### ISSUE TITLE
Splunk: 01-Probe Summary: Wireless Connection Graph has no data

### ISSUE THREAD

**Issue by neilmac64** [wifinigel/wiperf#27]
Original code states:
host=$host_name$ source="**wiperf-speedtes**t"| timechart avg(tx_rate_mbps) as "Tx PHY Rate" avg(rx_rate_mbps) as "Rx PHY Rate" avg(signal_level_dbm) as "Signal Level (dBm)"

To get this graph to work change to:
host=$host_name$ source="**wiperf-network**"| timechart avg(tx_rate_mbps) as "Tx PHY Rate"  avg(rx_rate_mbps) as "Rx PHY Rate" avg(signal_level_dbm) as "Signal Level (dBm)"

**Comment by wifinigel** [comment]
Hey Neil, thanks for the report. Will make sure this is fixed in the next release.

**Comment by wifinigel** [comment]
Checked wiperf source code and verified this correction has been applied.
