### ISSUE TITLE
Documentation PDF seems to be broken

### ISSUE THREAD

**Issue by patoberli** [wifinigel/wiperf#3]
Hi,
I can't open the file docs/WLANPi Wiperf Probe - Splunk Build.pdf in the browser, neither after downloading and trying Acrobat Reader. Reader informs that the file is corrupt.
Thanks
Patrick

**Comment by wifinigel** [comment]
I think the issue is you have to follow the link from the top level ReadMe. Try this link: https://github.com/wifinigel/wiperf/raw/master/docs/WLANPi%20Wiperf%20Probe%20-%20Splunk%20Build.pdf

**Comment by patoberli** [comment]
Not working for me. Acrobat Reader for Windows (current version, updated today) only says "There was an error opening this document. The file is damaged and could not be repaired."

**Comment by wifinigel** [comment]
OK, try the new version (just pushed to GitHub). I don't think Git was handling it as a binary file.

**Comment by patoberli** [comment]
Working now, thanks :)
