### ISSUE TITLE
Remote Configuration Server

### ISSUE THREAD

**Issue by willcurtis** [wifinigel/wiperf#45]
Hi Guys,

I have confgured my WLANPi to use a remote config server but it appears to be failing to read the contents of the file, below is the output from the wiperf_agent.log 

Am I using the correct URL or is the config file in the wrong format?

2021-01-20 21:15:05,254 - Probe_Log - INFO - Checking if we use remote cfg file...
2021-01-20 21:15:05,254 - Probe_Log - INFO - Checking cfg last-read timestamp...
2021-01-20 21:15:05,255 - Probe_Log - INFO - Timestamp file does not exist, creating...
2021-01-20 21:15:05,256 - Probe_Log - INFO - Writing current time to cfg timestamp file...
2021-01-20 21:15:05,257 - Probe_Log - INFO - Written OK.
2021-01-20 21:15:05,258 - Probe_Log - DEBUG - Checking time diff, time now: 1611177305, last read time: 0
2021-01-20 21:15:05,259 - Probe_Log - INFO - Time to read remote cfg file...
2021-01-20 21:15:05,260 - Probe_Log - INFO - Trying to pull config file from : https://github.com/********/*******/raw/main/config.ini
2021-01-20 21:15:05,830 - Probe_Log - INFO - Config file pulled OK.
2021-01-20 21:15:05,834 - Probe_Log - INFO - No data detected in cfg file, nothing written to file (check file URL)
2021-01-20 21:15:05,836 - Probe_Log - INFO - No lock file found. Creating lock file.

Thanks in advance!

**Comment by wifinigel** [comment]
Hi Will,

Looking in to the code, it looks as although a good http response is being received back from GitHub (code 200), it's probably not the content of the config file that you're getting back in the response.

I think when I've looked in to this in the past, it tends to be either the auth key is wrong (or not correctly applied on GitHub), or the URL being used for the config file is incorrect.

I'll have to set this up and test as it's been a while since I looked in to this.

Are you using a personal access token or a username/pwd to authenticate?

Maybe try using  a username/pwd combo for testing with a browser and make sure you get back the config file you expect if you manually browse to the raw file on github? 

Let me know how it goes. :)

Regards

Nigel.

**Comment by willcurtis** [comment]
Thanks Nigel, Thats great, I will have a play with that and let you know.

Regards, Will.

**Comment by wifinigel** [comment]
Hi @willcurtis, just wondered how you got on with getting the remote server going?

Regards

Nigel.

**Comment by Blazerfi** [comment]
I was just testing this and got the same error as @willcurtis.  I used the URL from the Raw file and it worked.

**Comment by wifinigel** [comment]
I just set this up and it worked OK for me.

There is a bug in the code that means that it reports that the config file has been pulled OK when it has actually failed. Once I fix that, you should be able to get a better indication what is going on.

When creating your personal access token, you need to have permissions set as follows (created via Settings > Developer Settings > Personal Access Tokens > Generate New Token) :

![image](https://user-images.githubusercontent.com/19818404/106208037-a67db680-61ba-11eb-9625-876b143f470e.png)

As long as your personal access token matches and the path to the raw file on Guthub matches, it should still work. 

You'll have to give me a day or two to push out a patch for you to try.

Regards

Nigel.

**Comment by willcurtis** [comment]
No difference here im afraid, im using the raw URL with the config.ini on the end, should this be included or omitted?

**Comment by wifinigel** [comment]
The name of the file does not have to be config.ini - it gets converted to the correct filename once downloaded.

For instance, I am testing now and my URL string is:

```
cfg_url: https://raw.githubusercontent.com/wifinigel/<repo_name_removed>/master/neo3.ini
```
HTH

**Comment by wifinigel** [comment]
BTW, one thing I notice recently is that when you publish a file on GitHub, it takes a few minutes to actually be downloadable. 

I just made some changes and it took a while before the new file was available. Leave it a few minutes before writing it off as a failure after you make a change. I see similar effects when publishing code too.

**Comment by wifinigel** [comment]
OK, I've updated the poller module that should have the fixes you need. It has additional debugging info too if you enable debug within config.ini. You should see the poller module move from v0.3.0 to v0.3.1. I'll release this officially once you guys have tested it. 

Here is the output from the upgrade process you need to follow:

```
wiperf@wiperf-neo3:~$ sudo pip3 list
Package             Version  
------------------- ---------
certifi             2020.12.5
chardet             4.0.0    
distro-info         0.21     
idna                2.10     
influxdb            5.3.1    
influxdb-client     1.13.0   
iotop               0.6      
iperf3              0.1.11   
msgpack             1.0.2    
pip                 18.1     
pycurl              7.43.0.2 
PyGObject           3.30.4   
python-apt          1.8.4.3  
python-dateutil     2.8.1    
pytz                2020.5   
requests            2.25.1   
Rx                  3.1.1    
setuptools          52.0.0   
six                 1.15.0   
speedtest-cli       2.1.2    
timeout-decorator   0.5.0    
unattended-upgrades 0.1      
urllib3             1.26.3   
wheel               0.36.2   
wiperf-poller       0.3.0    <<<<<<<<<

wiperf@wiperf-neo3:~$ sudo pip3 install --upgrade wiperf-poller
Collecting wiperf-poller
  Downloading https://files.pythonhosted.org/packages/c2/ed/840ab8cd7cbcdd0936f7223f38342f379918513da9d80225486667e6c515/wiperf_poller-0.3.1-py3-none-any.whl (78kB)
    100% |████████████████████████████████| 81kB 1.5MB/s 
Requirement already satisfied, skipping upgrade: speedtest-cli in /usr/local/lib/python3.7/dist-packages (from wiperf-poller) (2.1.2)
Requirement already satisfied, skipping upgrade: influxdb in /usr/local/lib/python3.7/dist-packages (from wiperf-poller) (5.3.1)
Requirement already satisfied, skipping upgrade: influxdb-client in /usr/local/lib/python3.7/dist-packages (from wiperf-poller) (1.13.0)
Requirement already satisfied, skipping upgrade: iperf3 in /usr/local/lib/python3.7/dist-packages (from wiperf-poller) (0.1.11)
Requirement already satisfied, skipping upgrade: timeout-decorator in /usr/local/lib/python3.7/dist-packages (from wiperf-poller) (0.5.0)
Requirement already satisfied, skipping upgrade: msgpack in /usr/local/lib/python3.7/dist-packages (from influxdb->wiperf-poller) (1.0.2)
Requirement already satisfied, skipping upgrade: pytz in /usr/local/lib/python3.7/dist-packages (from influxdb->wiperf-poller) (2020.5)
Requirement already satisfied, skipping upgrade: python-dateutil>=2.6.0 in /usr/local/lib/python3.7/dist-packages (from influxdb->wiperf-poller) (2.8.1)
Requirement already satisfied, skipping upgrade: six>=1.10.0 in /usr/local/lib/python3.7/dist-packages (from influxdb->wiperf-poller) (1.15.0)
Requirement already satisfied, skipping upgrade: requests>=2.17.0 in /usr/local/lib/python3.7/dist-packages (from influxdb->wiperf-poller) (2.25.1)
Requirement already satisfied, skipping upgrade: rx>=3.0.1 in /usr/local/lib/python3.7/dist-packages (from influxdb-client->wiperf-poller) (3.1.1)
Requirement already satisfied, skipping upgrade: setuptools>=21.0.0 in /usr/local/lib/python3.7/dist-packages (from influxdb-client->wiperf-poller) (52.0.0)
Requirement already satisfied, skipping upgrade: certifi>=14.05.14 in /usr/local/lib/python3.7/dist-packages (from influxdb-client->wiperf-poller) (2020.12.5)
Requirement already satisfied, skipping upgrade: urllib3>=1.15.1 in /usr/local/lib/python3.7/dist-packages (from influxdb-client->wiperf-poller) (1.26.3)
Requirement already satisfied, skipping upgrade: idna<3,>=2.5 in /usr/local/lib/python3.7/dist-packages (from requests>=2.17.0->influxdb->wiperf-poller) (2.10)
Requirement already satisfied, skipping upgrade: chardet<5,>=3.0.2 in /usr/local/lib/python3.7/dist-packages (from requests>=2.17.0->influxdb->wiperf-poller) (4.0.0)
Installing collected packages: wiperf-poller
  Found existing installation: wiperf-poller 0.3.0
    Uninstalling wiperf-poller-0.3.0:
      Successfully uninstalled wiperf-poller-0.3.0
Successfully installed wiperf-poller-0.3.1 <<<<<<<

wiperf@wiperf-neo3:~$ sudo pip3 list
Package             Version  
------------------- ---------
certifi             2020.12.5
chardet             4.0.0    
distro-info         0.21     
idna                2.10     
influxdb            5.3.1    
influxdb-client     1.13.0   
iotop               0.6      
iperf3              0.1.11   
msgpack             1.0.2    
pip                 18.1     
pycurl              7.43.0.2 
PyGObject           3.30.4   
python-apt          1.8.4.3  
python-dateutil     2.8.1    
pytz                2020.5   
requests            2.25.1   
Rx                  3.1.1    
setuptools          52.0.0   
six                 1.15.0   
speedtest-cli       2.1.2    
timeout-decorator   0.5.0    
unattended-upgrades 0.1      
urllib3             1.26.3   
wheel               0.36.2   
wiperf-poller       0.3.1    <<<<<<<<
wiperf@wiperf-neo3:~$ 
```

**Comment by willcurtis** [comment]
Thanks Nigel, it is now working, I deleted the config from the device and the github repository and rebuilt them, I imagine it was something within the config but doing a stare and compare I couldn't see a difference. Many Thanks for your assistance!

**Comment by Blazerfi** [comment]
I'm not sure if it is something that I did, but I am not getting the error after upgrading and changing to the new config.ini file. 

 ERROR - Issue sending data to Influx: 400: {"error":"partial write: field type conflict: input field \"percent_loss\" on measurement \"wiperf-ping\" is type integer, already exists as type string dropped=1"

**Comment by wifinigel** [comment]
@Blazerfi Yes, sounds like you are hitting this: https://wifinigel.github.io/wiperf/whats_new_v2.1/#release-notes (see note 5).

There was an update to some database fields that were incorrectly created as strings in older versions of wiperf.

I'm pretty sure this will fix it for you.

Nigel.

**Comment by Blazerfi** [comment]
ah, sorry. I will check it out. I am usually better at checking those notes.

**Comment by wifinigel** [comment]
No probs...there is a lot of info to wade through.

**Comment by Blazerfi** [comment]
I know what I did now. I went from 2.0 to 2.2, so I didn't read the notes for 2.1.

**Comment by Blazerfi** [comment]
Np, reading is fundamental :-)

**Comment by wifinigel** [comment]
Note added....thanks for the heads up.
