### ISSUE TITLE
Run wiperf without Splunk settings

### ISSUE THREAD

**Issue by lealog** [wifinigel/wiperf#9]
Currently I don't have splunk servers. Can I continue using wiperf without the splunk?

I'm always receiving the following error:
2020-02-25 01:11:12,689 - Probe_Log - INFO - *****************************************************
2020-02-25 01:11:12,690 - Probe_Log - INFO -  Starting logging...
2020-02-25 01:11:12,690 - Probe_Log - INFO - *****************************************************
2020-02-25 01:11:12,697 - Probe_Log - ERROR - No value in config.ini for field value: data_host - exiting...

Thanks.

**Comment by wifinigel** [comment]
No, currently wiperf will only run it has somewhere to send to data. If it has no management server or it cannot reach the mgt port of the server, it will exit as there is no point in running.

Do you see a use-case when it might be useful to run anyhow? As there is currently no local reporting system, there isn't (currently) much point in running the test to gather data as far as I can see..

I'm sure this may change in the future, but I don't see the use case at the moment?

Thanks for your submission.

**Comment by lealog** [comment]
Hi Nigel,

The use case is to have the report available locally without an external platform to process the information.
This feature can be useful for people that dont have possibility to have splunk platform.

Do you see huge effort to have this new feature implemented?

**Comment by wifinigel** [comment]
The best I can do in the short term is dump data in to  local CSV file on the WLAN Pi/RPi itself. But in terms of creating a local reporting capability on the WLAN Pi/RPi itself, I think that is quite some way off as it's a very big task for me.

**Comment by lealog** [comment]
Hi Nigel,

Having the .csv with the timestamp for each test and saved locally it's enough. If someone wants to create fancy reports will need to export the .csv files.

Do you think this is feasible?
Thanks.

**Comment by wifinigel** [comment]
I already have most of the code for a local CSV dump, so I'll re-visit it to get it to be a selectable in the config file and look at making sure the file sizes don't get too big.

**Comment by lealog** [comment]
Thanks.

**Comment by wifinigel** [comment]
Moved to issue: https://github.com/wifinigel/wiperf/issues/24
